---
server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  logging:
    level:
      root: INFO
      org.hibernate:  INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.shihui.persistence: DEBUG
  eureka:
    client:
      serviceUrl:
        defaultZone:  http://dicovery:8761/eureka
    instance:
      preferIpAddress: true
  profiles: user-8000


---
server:
  port: 8001
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  logging:
    level:
      root: INFO
      org.hibernate:  INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.shihui.persistence: DEBUG
  eureka:
    client:
      serviceUrl:
        defaultZone:  http://dicovery:8761/eureka
    instance:
      preferIpAddress: true
  profiles: user-8001
